version: '3'

services:
    mysql:
        image: mysql
        volumes:
            - ./db:/var/lib/mysql
        environment:
            - "MYSQL_USER=root"
            - "MYSQL_ROOT_PASSWORD=root"
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        ports:
            - "8090:80"
        links:
            - mysql:db
    wordpress:
        image: wordpress
        volumes:
            - ./wordpress:/var/www/html/
        depends_on:
            - mysql
        ports:
            - "8081:80"
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: root
            WORDPRESS_DB_NAME: wordpress